using Legacy2Modern.Business.Models.AI;
using Legacy2Modern.Business.Services;
using Legacy2Modern.Business.Services.AI;
using System;
using System.Text;

namespace Legacy2Modern.Web
{
    public partial class ModernizationPlanningTest
        : System.Web.UI.Page
    {
        protected void btnGeneratePlan_Click(
            object sender,
            EventArgs e)
        {
            try
            {
                var findingService =
                    new ModernizationFindingService();

                var findings =
                    findingService.GetExportData();

                if (findings == null ||
                    findings.Count == 0)
                {
                    throw new InvalidOperationException(
                        "No modernization findings are available.");
                }

                /*
                 * For M6.10 we need the recommendations
                 * generated by the existing M5 analysis flow.
                 *
                 * The existing analysis service is reused here
                 * only to obtain those recommendations.
                 */

                var promptBuilder =
                    new ModernizationPromptBuilder();

                var requestBuilder =
                    new ModernizationAIRequestBuilder(
                        promptBuilder);

                var providerConfiguration =
                    new AIProviderConfiguration
                    {
                        ProviderName =
                            System.Configuration.ConfigurationManager
                                .AppSettings["AIProvider"],

                        ModelName =
                            System.Configuration.ConfigurationManager
                                .AppSettings["AIModel"],

                        Endpoint =
                            System.Configuration.ConfigurationManager
                                .AppSettings["AIEndpoint"],

                        TimeoutSeconds =
                            int.Parse(
                                System.Configuration.ConfigurationManager
                                    .AppSettings["AITimeoutSeconds"])
                    };

                var providerFactory =
                    new AIProviderFactory();

                var primaryProvider =
                    providerFactory.Create(
                        providerConfiguration);

                var fallbackProvider =
                    new MockModernizationAIService();

                var fallbackConfiguration =
                    new AIFallbackConfiguration
                    {
                        Enabled =
                            bool.Parse(
                                System.Configuration.ConfigurationManager
                                    .AppSettings["AIFallbackEnabled"]),

                        ProviderName =
                            System.Configuration.ConfigurationManager
                                .AppSettings["AIFallbackProvider"]
                    };

                var orchestrator =
                    new AIProviderOrchestrator(
                        primaryProvider,
                        fallbackProvider,
                        fallbackConfiguration);

                var aiService =
                    new ModernizationAIService(
                        orchestrator);

                var analysisService =
                    new ModernizationAnalysisService(
                        findingService,
                        promptBuilder,
                        requestBuilder,
                        aiService);

                var analysis =
                    analysisService.Analyze();

                if (analysis == null ||
                    analysis.Recommendations == null ||
                    analysis.Recommendations.Count == 0)
                {
                    throw new InvalidOperationException(
                        "No AI recommendations were generated.");
                }

                var planningContext =
                    new ModernizationPlanningContext
                    {
                        ApplicationName =
                            "Legacy2Modern-AI",

                        ApplicationDescription =
                            "A legacy ASP.NET Web Forms application being incrementally modernized.",

                        TechnologyStack =
                            "ASP.NET Web Forms, .NET Framework 4.8, C#, Entity Framework 6, SQL Server",

                        ModernizationGoal =
                            "Identify practical modernization opportunities while minimizing business disruption.",

                        Findings =
                            findings,

                        Recommendations =
                            analysis.Recommendations
                    };

                var planningPromptBuilder =
                    new ModernizationPlanningPromptBuilder();

                var planningRequestBuilder =
                    new ModernizationPlanningRequestBuilder(
                        planningPromptBuilder);

                var planningResponseParser =
                    new ModernizationPlanningResponseParser();

                var planningResponseValidator =
                    new ModernizationPlanningResponseValidator();

                var planningProviderFactory =
                    new AIPlanningProviderFactory(
                        planningResponseParser,
                        planningResponseValidator);

                var planningProvider =
                    planningProviderFactory.Create(
                        providerConfiguration);

                var planningService =
                    new ModernizationPlanningService(
                        planningRequestBuilder,
                        planningProvider);

                var response =
                    planningService.CreatePlan(
                        planningContext);

                DisplayPlan(response);
            }
            catch (Exception ex)
            {
                lblResult.Text =
                    "<pre>" +
                    Server.HtmlEncode(
                        ex.ToString()) +
                    "</pre>";
            }
        }

        private void DisplayPlan(
            ModernizationPlanningResponse response)
        {
            if (response == null ||
                response.Plan == null)
            {
                lblResult.Text =
                    "No modernization plan was returned.";

                return;
            }

            var plan =
                response.Plan;

            var output =
                new StringBuilder();

            output.AppendLine(
                "<h2>" +
                Server.HtmlEncode(
                    plan.PlanTitle) +
                "</h2>");

            output.AppendLine(
                "<p><strong>Provider:</strong> " +
                Server.HtmlEncode(
                    response.ProviderName) +
                "</p>");

            output.AppendLine(
                "<p><strong>Overall Strategy:</strong><br />" +
                Server.HtmlEncode(
                    plan.OverallStrategy) +
                "</p>");

            output.AppendLine(
                "<p><strong>Target Architecture:</strong><br />" +
                Server.HtmlEncode(
                    plan.TargetArchitecture) +
                "</p>");

            output.AppendLine(
                "<h3>Phases</h3>");

            foreach (var phase in plan.Phases)
            {
                output.AppendLine(
                    "<h4>Phase " +
                    phase.PhaseNumber +
                    ": " +
                    Server.HtmlEncode(
                        phase.PhaseName) +
                    "</h4>");

                output.AppendLine(
                    "<p><strong>Objective:</strong> " +
                    Server.HtmlEncode(
                        phase.Objective) +
                    "</p>");

                output.AppendLine(
                    "<p><strong>Rationale:</strong> " +
                    Server.HtmlEncode(
                        phase.Rationale) +
                    "</p>");
            }

            output.AppendLine(
                "<h3>Plan Items</h3>");

            foreach (var item in plan.Items)
            {
                output.AppendLine(
                    "<div>");

                output.AppendLine(
                    "<h4>" +
                    Server.HtmlEncode(
                        item.PlanItemId) +
                    " - " +
                    Server.HtmlEncode(
                        item.Title) +
                    "</h4>");

                output.AppendLine(
                    "<p><strong>Finding:</strong> " +
                    Server.HtmlEncode(
                        item.FindingId) +
                    "</p>");

                output.AppendLine(
                    "<p><strong>Action:</strong> " +
                    Server.HtmlEncode(
                        item.RecommendedAction) +
                    "</p>");

                output.AppendLine(
                    "<p><strong>Priority:</strong> " +
                    Server.HtmlEncode(
                        item.Priority) +
                    "</p>");

                output.AppendLine(
                    "<p><strong>Risk:</strong> " +
                    Server.HtmlEncode(
                        item.Risk) +
                    "</p>");

                output.AppendLine(
                    "<p><strong>Complexity:</strong> " +
                    Server.HtmlEncode(
                        item.Complexity) +
                    "</p>");

                output.AppendLine(
                    "</div>");
            }

            lblResult.Text =
                output.ToString();
        }
    }
}