//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy2Modern.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditLog
    {
        public long AuditLogId { get; set; }
        public string EntityName { get; set; }
        public Nullable<int> EntityId { get; set; }
        public string ActionName { get; set; }
        public Nullable<int> UserId { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
