//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy2Modern.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerContact
    {
        public int CustomerContactId { get; set; }
        public int CustomerId { get; set; }
        public string ContactType { get; set; }
        public string ContactValue { get; set; }
        public bool IsPrimary { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
