//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy2Modern.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest()
        {
            this.ServiceRequestComments = new HashSet<ServiceRequestComment>();
            this.ServiceRequestHistories = new HashSet<ServiceRequestHistory>();
        }
    
        public int ServiceRequestId { get; set; }
        public string RequestNumber { get; set; }
        public int CustomerId { get; set; }
        public Nullable<int> CustomerProductId { get; set; }
        public Nullable<int> AssignedToEmployeeId { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string RequestType { get; set; }
        public string Priority { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<System.DateTime> ClosedDate { get; set; }
        public Nullable<int> CreatedByEmployeeId { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerProduct CustomerProduct { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestComment> ServiceRequestComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestHistory> ServiceRequestHistories { get; set; }
    }
}
