//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy2Modern.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestHistory
    {
        public int ServiceRequestHistoryId { get; set; }
        public int ServiceRequestId { get; set; }
        public Nullable<int> ChangedByEmployeeId { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public string OldPriority { get; set; }
        public string NewPriority { get; set; }
        public string ChangeReason { get; set; }
        public System.DateTime ChangedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
