//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Legacy2Modern.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestComment
    {
        public int ServiceRequestCommentId { get; set; }
        public int ServiceRequestId { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string CommentText { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
    }
}
